# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# workflow 이름
name: Java CI with Gradle

# workflow를 발생시키는 이벤트 정의
on:
  push:
    branches: [ "main" ] # main 브랜치에 push 이벤트가 발생하면 job 실행
  pull_request:
    branches: [ "main" ] # main 브랜치에 pr 이벤트가 발생하면 job 실행

# job 정의
jobs:
  build: # job 이름
    runs-on: ubuntu-latest # 해당 job을 어떤 OS에서 실행할 것인지
    permissions:
      contents: read

    # job에 포함된 step 정의
    steps:
    - uses: actions/checkout@v4 # step에서 사용할 action - 레포지토리의 코드를 체크아웃
    - name: Set up JDK 17 # step 이름
      uses: actions/setup-java@v4 # JAVA JDK 설치
      with:
        java-version: '17' # 17버전
        distribution: 'temurin'

    ## application.yml 생성 후 secret 값 복붙
#    - uses: actions/checkout@v3
#    - run: mkdir -p ./src/main/resources
#    - run: cd ./src/main/resources
#    - run: touch ./application.yml
#    - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
#    - run: cat ./src/main/resources/application.yml

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0 - Gradle 설정

    - name: Build with Gradle Wrapper
      run: ./gradlew build # Gradle로 프로젝트 빌드

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build
